# cspell:ignore esbuild, unrs
packages:
  - apps/*
  - packages/*
  - tooling/*

allowUnusedPatches: false

catalog:
  "@types/node": ^24.5.1
  eslint: ^9.35.0
  babel-plugin-react-compiler: 19.1.0-rc.3
  typescript: ^5.9.2
  vite: ^7.1.5
  vite-plugin-inspect: ^11.3.3
  "@vitejs/plugin-react": ^5.0.3
  "@types/react": ^19.1.13
  "@types/react-dom": ^19.1.9
  "@stylexjs/babel-plugin": ^0.15.4
  "@stylexjs/postcss-plugin": ^0.15.4
  "@stylexjs/stylex": ^0.15.4
  react: 19.2.0-canary-128abcfa-20250917
  react-dom: 19.2.0-canary-128abcfa-20250917

onlyBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
  - unrs-resolver

overrides:
  eslint-import-resolver-typescript>eslint-plugin-import: "-"
  react: "catalog:"
  react-dom: "catalog:"
  vite: npm:rolldown-vite@latest

engineStrict: true
packageManagerStrictVersion: true
saveWorkspaceProtocol: true
linkWorkspacePackages: true
managePackageManagerVersions: false
verifyDepsBeforeRun: "error"
strictDepBuilds: true
