# cspell:ignore esbuild, unrs, jotai, nuqs, xyflow
packages:
  - apps/*
  - packages/*
  - tooling/*

allowUnusedPatches: false

catalog:
  "@types/node": ^24.1.0
  eslint: ^9.32.0
  babel-plugin-react-compiler: 19.1.0-rc.2
  typescript: ^5.8.3
  vite: ^7.0.6
  vite-plugin-inspect: ^11.3.0
  "@vitejs/plugin-react": ^4.7.0
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  "@stylexjs/babel-plugin": ^0.14.3
  "@stylexjs/postcss-plugin": ^0.14.3
  "@stylexjs/stylex": ^0.14.3
  react: 0.0.0-experimental-19baee81-20250725
  react-dom: 0.0.0-experimental-19baee81-20250725
  "@vitejs/plugin-rsc": https://pkg.pr.new/vitejs/vite-plugin-react/@vitejs/plugin-rsc-experimental@dbe0ce7

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  eslint-import-resolver-typescript>eslint-plugin-import: "-"
  vite: "npm:rolldown-vite@latest"

engineStrict: true
packageManagerStrictVersion: true
saveWorkspaceProtocol: true
linkWorkspacePackages: true
managePackageManagerVersions: false
verifyDepsBeforeRun: "error"
strictDepBuilds: true
