# cspell:ignore esbuild, unrs, jotai, nuqs, xyflow
packages:
  - apps/*
  - packages/*
  - tooling/*

allowUnusedPatches: false

catalog:
  "@types/node": ^24.0.15
  babel-plugin-react-compiler: 19.1.0-rc.2
  typescript: ^5.8.3
  vite: ^7.0.5
  vite-plugin-inspect: ^11.3.0
  "@vitejs/plugin-react": ^4.7.0
  "@types/react": ^19.1.8
  "@types/react-dom": ^19.1.6
  "@stylexjs/babel-plugin": ^0.14.2
  "@stylexjs/postcss-plugin": ^0.14.2
  "@stylexjs/stylex": ^0.14.2
  react: 0.0.0-experimental-dffacc7b-20250717
  react-dom: 0.0.0-experimental-dffacc7b-20250717
  "@vitejs/plugin-rsc": https://pkg.pr.new/vitejs/vite-plugin-react/@vitejs/plugin-rsc-experimental@968db53

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  eslint-import-resolver-typescript>eslint-plugin-import: "-"
  vite: "npm:rolldown-vite@latest"
