packages:
  - apps/*
  - packages/*
  - tooling/*

allowUnusedPatches: false

catalog:
  '@stylexjs/babel-plugin': ^0.15.3
  '@stylexjs/postcss-plugin': ^0.15.3
  '@stylexjs/stylex': ^0.15.3
  '@types/node': ^24.3.1
  '@types/react': ^19.1.12
  '@types/react-dom': ^19.1.9
  '@vitejs/plugin-react': ^5.0.2
  babel-plugin-react-compiler: 19.1.0-rc.3
  eslint: ^9.35.0
  react: 19.2.0-canary-de5a1b20-20250905
  react-dom: 19.2.0-canary-de5a1b20-20250905
  typescript: ^5.9.2
  vite: ^7.1.4
  vite-plugin-inspect: ^11.3.3

engineStrict: true

linkWorkspacePackages: true

managePackageManagerVersions: false

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

overrides:
  eslint-import-resolver-typescript>eslint-plugin-import: '-'
  react: 'catalog:'
  react-dom: 'catalog:'

packageManagerStrictVersion: true

saveWorkspaceProtocol: true

strictDepBuilds: true

verifyDepsBeforeRun: error
